function [fitresult, gof] = createFitSine(xgrid, x1,xstart,xend)
%CREATEFIT(XGRID,X1)
%  Create a fit.
%
%  Data for 'untitled fit 5' fit:
%      X Input: xgrid
%      Y Output: x1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Nov-2023 15:03:16
% have xdata exclusion points be fed into the function
% b1 is wave number k=2pi/lambda => lambda = 2pi/k


%% Fit: 'untitled fit 5'.
[xData, yData] = prepareCurveData( xgrid, x1 );

% Set up fittype and options.
ft = fittype( 'sin1' );
excludedPoints = (xData < xstart) | (xData > xend);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [0.260986226054489 50.7671430582814 0.532317294057775];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 5' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'x1 vs. xgrid', 'Excluded x1 vs. xgrid', 'untitled fit 5', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xgrid', 'Interpreter', 'none' );
ylabel( 'x1', 'Interpreter', 'none' );
grid on


